#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable
import pyarrow.parquet as pq

SOURCE_ROOT = Path(os.environ.get("SOURCE_ROOT", "source_runtime/minervini_picks/data")).resolve()
REPORT_PATH = Path(os.environ.get("REPORT_PATH", "docs/RUNTIME_SOURCE_PROBE.md"))

REPRESENTATIVES = [
    ("RAW market data", "raw/prices_raw_2026.parquet"),
    ("Adjusted research prices", "adj/prices_adj_2026.parquet"),
    ("Corporate actions", "reference/corporate_actions_ledger.parquet"),
    ("PIT industry", "reference/industry_pit.parquet"),
    ("Tradability", "reference/tradability.parquet"),
    ("Fundamentals", "fundamentals/financials.parquet"),
    ("Monthly revenue", "fundamentals/month_revenue.parquet"),
    ("Margin", "fundamentals/margin.parquet"),
    ("Institutional", "inst/stock_inst_2026.parquet"),
    ("KBar", "kbar/kbar_2026.parquet"),
]

DATE_CANDIDATES = (
    "date", "trade_date", "available_date", "known_date", "effective_date",
    "ex_date", "payment_date", "record_date", "datetime", "timestamp",
)
KEY_CANDIDATES = ("stock_id", "date", "datetime", "available_date", "event_id")
PIT_TOKENS = ("available", "known", "effective", "recorded", "download", "revision", "publish")
PROV_TOKENS = ("source", "provider", "dataset", "version", "revision", "download", "updated")

def esc(value: object) -> str:
    return str(value).replace("|", "/").replace("\n", " ")

def metadata_min_max(pf: pq.ParquetFile, column_name: str):
    names = pf.schema_arrow.names
    if column_name not in names:
        return None, None
    idx = names.index(column_name)
    lows, highs = [], []
    for rg_idx in range(pf.metadata.num_row_groups):
        col = pf.metadata.row_group(rg_idx).column(idx)
        stats = col.statistics
        if stats is not None and stats.has_min_max:
            lows.append(stats.min)
            highs.append(stats.max)
    if not lows:
        return None, None
    try:
        return min(lows), max(highs)
    except TypeError:
        return lows[0], highs[-1]

def names_matching(names: Iterable[str], tokens: Iterable[str]) -> list[str]:
    return [name for name in names if any(token in name.lower() for token in tokens)]

def inspect(label: str, rel: str) -> dict[str, object]:
    path = (SOURCE_ROOT / rel).resolve()
    if SOURCE_ROOT not in path.parents:
        raise RuntimeError("path escaped source root: " + rel)
    out: dict[str, object] = {
        "family": label,
        "path": rel,
        "readable": path.is_file() and os.access(path, os.R_OK),
    }
    if not out["readable"]:
        return out

    pf = pq.ParquetFile(path)
    schema = pf.schema_arrow
    names = schema.names
    out.update(
        size_mb=round(path.stat().st_size / 1024 / 1024, 2),
        rows=pf.metadata.num_rows,
        row_groups=pf.metadata.num_row_groups,
        columns=len(names),
        likely_keys=", ".join([n for n in KEY_CANDIDATES if n in names]) or "UNKNOWN",
        pit_fields=", ".join(names_matching(names, PIT_TOKENS)) or "NONE OBSERVED",
        provenance_fields=", ".join(names_matching(names, PROV_TOKENS)) or "NONE OBSERVED",
    )
    date_name = next((n for n in DATE_CANDIDATES if n in names), None)
    if date_name:
        lo, hi = metadata_min_max(pf, date_name)
        out["date_field"] = date_name
        out["date_min"] = lo if lo is not None else "NO_METADATA_STATS"
        out["date_max"] = hi if hi is not None else "NO_METADATA_STATS"
    else:
        out["date_field"] = "NONE"
        out["date_min"] = "N/A"
        out["date_max"] = "N/A"
    return out

def main() -> None:
    if not SOURCE_ROOT.is_dir():
        raise SystemExit("BLOCKED: source root does not exist: " + str(SOURCE_ROOT))

    results = [inspect(label, rel) for label, rel in REPRESENTATIVES]
    missing = [r for r in results if not r["readable"]]
    status = "DONE" if not missing else "BLOCKED"

    lines = [
        "# Runtime Source Probe",
        "",
        "Status: **" + status + "**",
        "",
        "Generated by the AstraQuant GitHub Actions runtime. Source checkout is transient and read-only.",
        "",
        "Source root used: " + str(SOURCE_ROOT),
        "",
        "## Representative parquet metadata",
        "",
        "| Family | File | Readable | Size MiB | Rows | Row groups | Columns | Date field | Min | Max | Likely keys | PIT fields | Provenance fields |",
        "|---|---|---:|---:|---:|---:|---:|---|---|---|---|---|---|",
    ]
    for r in results:
        lines.append(
            "| {family} | {path} | {readable} | {size_mb} | {rows} | {row_groups} | {columns} | "
            "{date_field} | {date_min} | {date_max} | {likely_keys} | {pit_fields} | {provenance_fields} |".format(
                family=esc(r["family"]), path=esc(r["path"]),
                readable="YES" if r["readable"] else "NO",
                size_mb=esc(r.get("size_mb", "N/A")), rows=esc(r.get("rows", "N/A")),
                row_groups=esc(r.get("row_groups", "N/A")), columns=esc(r.get("columns", "N/A")),
                date_field=esc(r.get("date_field", "N/A")), date_min=esc(r.get("date_min", "N/A")),
                date_max=esc(r.get("date_max", "N/A")), likely_keys=esc(r.get("likely_keys", "N/A")),
                pit_fields=esc(r.get("pit_fields", "N/A")),
                provenance_fields=esc(r.get("provenance_fields", "N/A")),
            )
        )

    lines += [
        "",
        "## Guardrails",
        "",
        "- Source repository uses the fine-grained read-only token.",
        "- Source checkout credentials are not persisted by actions/checkout.",
        "- Source tree is made filesystem read-only before the probe.",
        "- Probe uses parquet footer/metadata reads only; no full-table scan.",
        "- No source data is added to AstraQuant Git.",
        "",
        "## Result",
        "",
    ]
    if missing:
        lines.append("Blocked because representative files were missing or unreadable:")
        for r in missing:
            lines.append("- " + str(r["path"]))
    else:
        lines.append("All ten representative source families were readable.")
        lines.append("")
        lines.append("Next small task: canonical parquet inventory without backtesting.")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

if __name__ == "__main__":
    main()
